# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/v0.41.0/schema/config.json
git:
  paging:
    colorArg: always
    pager: delta --dark --color-only --paging=never
gui:
  showFileTree: false
  nerdFontsVersion: '3'
  theme:
    selectedLineBgColor:
      - reverse
      - bold
